### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by nocnokneo** [JochenKalmbach/StackWalker#1]
From the codeproject.org article, it looks like this is intended to be BSD license, but the code needs to explicitly state so here in the repo with a `LICENSE` file. See:

- https://choosealicense.com/
- https://help.github.com/articles/licensing-a-repository/

**Comment by JochenKalmbach** [comment]
Thanks...license added.

**Comment by nocnokneo** [comment]
Thanks!
