### ISSUE TITLE
Unable to symbolize stack traces when using /DEBUG:fastlink

### ISSUE THREAD

**Issue by Rseding91** [JochenKalmbach/StackWalker#2]
I'm not sure if that's something that can be fixed but I didn't see anything saying it explicitly wasn't supported so I figured I'd mention it.

https://blogs.msdn.microsoft.com/vcblog/2014/11/12/speeding-up-the-incremental-developer-build-scenario/

**Comment by dquist** [comment]
Good catch, I was confused as to why it was the class itself was throwing exceptions. This should be added to the readme as `/DEBUG:fastlink` is enabled by default in VS2015+.

**Comment by Rseding91** [comment]
@JochenKalmbach @danquist an update on this: LoadLibrary("dbghelp.dll") loads what ever version of dbghelp.dll is in C:\Windows\System32\ which is a very old version of the dll. If a newer version of dbghelp is placed along side the executable it can generates proper stack traces when using /debug:fastlink.
