### ISSUE TITLE
Putting #include "StackWalker.h" as first include

### ISSUE THREAD

**Issue by Nampo** [JochenKalmbach/StackWalker#27]
In StackWalker.cpp, it would be helpful to move
#include "StackWalker.h"
as first include.
This will enable it to be used as-is with third party softwares like Unreal Engine 4, that requires the header of any cpp file to be the first included file (it uses custom build tools).
It's also a good practice, as it helps to detect possible undeclared identifiers in the header that just compile by chance by being included later in the cpp.

**Comment by JochenKalmbach** [comment]
Solved with commit 
https://github.com/JochenKalmbach/StackWalker/commit/020706a2972bff842d8976ef81825f57e197eea5
