### ISSUE TITLE
Is it able to get the callstacks without pdb?

### ISSUE THREAD

**Issue by ldlchina** [JochenKalmbach/StackWalker#33]
Cant get the stack if remove the pdb.

Has pdb
`
l:\dev\testcrash\testcrash\stackwalker.cpp (1096): StackWalker::ShowCallstack
l:\dev\testcrash\testcrash\testcrash.cpp (83): `anonymous namespace'::dumpCallStacks
l:\dev\testcrash\testcrash\testcrash.cpp (119): `anonymous namespace'::test
l:\dev\testcrash\testcrash\testcrash.cpp (143): main
`

Has not pdb
`
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF647322465)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF647322465)
00007FF647322465 (TestCrash): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF64732363D)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF64732363D)
00007FF64732363D (TestCrash): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF6473239E6)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF6473239E6)
00007FF6473239E6 (TestCrash): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF647323AB6)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF647323AB6)
00007FF647323AB6 (TestCrash): (filename not available): (function-name not available)
ERROR: SymGetSymFromAddr64, GetLastError: 487 (Address: 00007FF64732485D)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF64732485D)
00007FF64732485D (TestCrash): (filename not available): (function-name not available)
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF905E63034)
00007FF905E63034 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FF907441471)
`

Thanks,
Liu

**Comment by JochenKalmbach** [comment]
This is by design. Please see the documentation.

**Comment by ldlchina** [comment]
@JochenKalmbach ,

is it able to get the function names if there are no pdbs? Like below:
(module:TestCrash) File: (filename not available): StackWalker::ShowCallstack 
(module:TestCrash) File: (filename not available): anonymous namespace'::dumpCallStacks

If yes, how to make it work? I saw some application can get the function names at crash by using StackWalker without pdbs.

Thanks again.
Liu

**Comment by JochenKalmbach** [comment]
@ldlchina You just need to embedd the symbols in your EXE/DLL... 
This was supported with older VC++ compiler/linkers… but it seems, that MS removed this feature... see also: https://stackoverflow.com/questions/3576973/embed-pdb-debug-symbol-information-into-an-exe-file-in-visual-studio

PS: Why do you need it? For crash-dumping, please use Dump-files!
