### ISSUE TITLE
The second and later frame's line number is not correct, must change the use of SymGetLineFromAddr64()

### ISSUE THREAD

**Issue by cq168tomtom** [JochenKalmbach/StackWalker#37]

**Comment by cq168tomtom** [comment]
// tjl, fix line print, 2019.06.19
        if (frameNum == 0)
        {
          if (this->m_sw->pSGLFA(this->m_hProcess, s.AddrPC.Offset, &(csEntry.offsetFromLine),
                                 &Line) != FALSE)
          {
            csEntry.lineNumber = Line.LineNumber;
            MyStrCpy(csEntry.lineFileName, STACKWALK_MAX_NAMELEN, Line.FileName);
          }
          else
          {
            this->OnDbgHelpErr("SymGetLineFromAddr64", GetLastError(), s.AddrPC.Offset);
          }
        }
        else
        {
          // tjl,  2019.06.18. if not first frame, the address must to plus 1, so get the correct line number!
          if (this->m_sw->pSGLFA(this->m_hProcess, s.AddrPC.Offset-1, &(csEntry.offsetFromLine),
                                 &Line) != FALSE)
          {
            csEntry.lineNumber = Line.LineNumber;
            MyStrCpy(csEntry.lineFileName, STACKWALK_MAX_NAMELEN, Line.FileName);
          }
          else
          {
            this->OnDbgHelpErr("SymGetLineFromAddr64", GetLastError(), s.AddrPC.Offset);
          }
        }

**Comment by cq168tomtom** [comment]
in second and later frame,  i use like this:
SymGetLineFromAddr64(this->m_hProcess, s.AddrPC.Offset-1, &(csEntry.offsetFromLine);
so, is this a bug of   SymGetLineFromAddr64()?

**Comment by JochenKalmbach** [comment]
This is most likely the return address of the caller...and the optimization of the code...so the SymGetLineFromAddr64 is correct… it can´t see that the call was optimized...
