### ISSUE TITLE
Stalkwalker does not return any symbols in VS 2015 with the /clr compile option

### ISSUE THREAD

**Issue by DragonPearlJasmine** [JochenKalmbach/StackWalker#40]
I have an application that contains both c++ and C# code, so I'm compiling with the /clr compile option. However I think that option is causing Stackwalker to not return any symbols.

**Comment by JochenKalmbach** [comment]
Stackwalker works only for native code. What do you want to achive?
If you want to take a look at the managed callstackm, you can use `new StackTrace(true);`
