### ISSUE TITLE
Is it possible to seperate the creation of the callstack from formatting it?

### ISSUE THREAD

**Issue by simonvanbernem** [JochenKalmbach/StackWalker#52]
I have a usecase where I want to collect A LOT of callstacks (one for every allocation) from the current thread, but the information is only needed if an error occurs (we detect a double free, access violation, etc.). In debug mode, calling ShowCallstack takes about 1ms, which is too long to be practical with lots of allocations happening.

I wondered if it is possible to seperate the process of gathering the callstack (as in the addresses) from formatting the callstack (turning addresses into meaningful text). If that was possible, I could just save the addresses on every allocation and only format them when the error occurs.

Would a function like "give me the fully formated string for this address" be in scope for StackWalker? Is this even possible in this way, or is more information needed? Would it yield the speedup that I hope for?

I thought about trying it for myself using `CaptureStackBackTrace` to gather the addresses and then `SymGetLineFromAddr64` to obtain the strings, but the API looks a bit less straight forward than I had hoped for, so I thought I'd ask first.

**Comment by equalman** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by simonvanbernem** [comment]
lol

**Comment by JochenKalmbach** [comment]
I used to have the same requirement... therefor I invented the "leakfinder". See also:
http://blog.kalmbachnet.de/files/04-09-08__leakfinder.htm

**Comment by simonvanbernem** [comment]
So I guess that's a no then? I want to do more than just finding leaks, so I have no use for leakfinder. Also, the Stackwalkher.h and .cpp in leakfinder seem to be completely unrelated to the ones in Stackwalker? That's certainly confusing.

Since I'm only on windows for now, I was able to use the approach using `CaptureStackBackTrace` I was mentioning, so I personally don't need this solution anymore, but I still think adding this functionality to stackwalker would be valuable: By saying "just use leakfinder" every person that has a slightly different usecase that doesn't fit goes home empty handed. They have to do the entire work on their own now, eventhough Stackwalker already contains all the necessary functionality, but just doesn't expose it at a high enough granularity. If capturing the callstack and turning it into a string were separate parts of the API, those people would save a great amount of work, and it would make the entire library more useful, even in use cases that have nothing to do with allocation at all (e.g.: doing the costly conversion to a string on a separate thread).
