### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by AenBleidd** [JochenKalmbach/StackWalker#56]
The last release 1.20 was made almost 5 years ago. Since then there were some significant changes made.
It would be nice to have a new tag created for a new release to be used in dependency managers like [vcpkg](https://github.com/microsoft/vcpkg).
Thank you in advance

**Comment by BillyONeal** [comment]
https://github.com/microsoft/vcpkg/pull/30909/ I can confirm adding patches from 5 years ago is a bit 🥲

**Comment by JochenKalmbach** [comment]
https://github.com/JochenKalmbach/StackWalker/releases/tag/2023-06-24

**Comment by equalman** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
