### ISSUE TITLE
CRT Buffer Overrun detected when function name is very long

### ISSUE THREAD

**Issue by BikingGlobetrotter** [JochenKalmbach/StackWalker#8]
I experienced a crashed when using StackWalker, when the of a function on the stack does not fit in the _snprintf_s buffer, so if the resulting string is longer then STACKWALK_MAX_NAMELEN (1024). In that case, CRT terminates the process. This can happen e.g. when using boost data structures that use a lot of templates (e.g. boost::unordered::detail::func::construct_value_impl<std::allocator<boost::unordered::detail::ptr_node<std::pair<boost::thread::id const ,std::vector<cncsim::mwCNCSimApiLogger::CallInfo,std::allocator<cncsim::mwCNCSimApiLogger::CallInfo> > > > >,boost::thread::id const ,std::vector<cncsim::mwCNCSimApiLogger::CallInfo,std::allocator<cncsim::mwCNCSimApiLogger::CallInfo> >,boost::unordered::piecewise_construct_t const & __ptr64,boost::tuples::tuple<boost::thread::id,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type>,boost::tuples::tuple<boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type,boost::tuples::null_type> >)

Using _TRUNCATE when calling _snprintf_s, will truncate the function name instead of treating this as an error (see https://msdn.microsoft.com/en-us/library/ms175769.aspx)

**Comment by BikingGlobetrotter** [comment]
This my pull request to solve the issue: #9

**Comment by JochenKalmbach** [comment]
Thanks for reporting this issue. We have fixed this bug in the latest version. #

**Comment by BikingGlobetrotter** [comment]
Unfortunately, you did not get my point concerning the buffer overrun. It is not about a non-null terminated string. The problem is that CRT terminates the process when the string will not fit in the buffer provided to _snprintf_s if _TRUNCATE is not used. See the following example

    const size_t buffer_size = 10;
    char buffer[buffer_size];
    const char* fillInText = "This text exceeds the buffer size";

    // A) Write truncated string using _TRUNCATE (available since VS2008, don't know if available earlier as well)
    _snprintf_s(buffer, _TRUNCATE, "Text: %s", fillInText);
    // _snprintf_s ensures string is null terminated
    // see https://msdn.microsoft.com/en-us/library/f30dzcf6(v=vs.90).aspx
    // If count is _TRUNCATE, then _snprintf_s writes as much of the string as will fit in buffer
    // while leaving room for a terminating null. If the entire string (with terminating null) fits in buffer,
    //then _snprintf_s returns the number of characters written (not including the terminating null);
    // otherwise, _snprintf_s returns -1 to indicate that truncation occurred.
    std::cout << buffer << std::endl;

    // B) write non truncated string
    _snprintf_s(buffer, buffer_size, "Text: %s", fillInText);
    // DEBUG ASSERTION: Expression : ("Buffer too small", 0)
    // File : f:\dd\vctools\crt\crtw32\stdio\vsprintf.c
    // Line : 322

    // Program crashes with following message
    // Microsoft Visual Studio C Runtime Library has detected a fatal error in MfcTestApplication.exe.

    // Line not reached at runtime
    std::cout << buffer << std::endl; 

As you can see using B) the program crashes, while A) allows the process to continue. Since having many stack frames with a lot of templated functions may exceed the default buffer size, I suggest to use _TRUNCATE which is provided since VS2008 (probably the same as _snprintf_s anyway).
As already said, this can be solved using my pull request #9

**Comment by JochenKalmbach** [comment]
Yes, sorry... I now see the point.... will try to fix this...

**Comment by JochenKalmbach** [comment]
Should be solved in the commit 
https://github.com/JochenKalmbach/StackWalker/commit/8ad0f01228d95476e81c2f1b93a9240e8aa2beed
